language: cpp
os: linux
compiler:
  - gcc
  - clang

before_install:
  - test -n $CC && unset CC

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgomp1
      # - gcc-6

script:
  - export OMP_NUM_THREADS=2
  - export LD_LIBRARY_PATH=$(if [[ $CXX == "clang++" ]]; then echo -n '/usr/local/clang/lib'; fi)
  - mkdir build
  - cd build
  - cmake .. -DUSE_OPENMP=OFF
  - make
  - rm -rf *
  - cmake .. -DUSE_OPENMP=ON
  - make
