name: C/C++ CI

on: [push]
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@master
    - name: build directory
      run: mkdir build && cd build
    - name: configure
      run: cmake .
    - name: build
      run: cmake --build .
      
