name: Code Formatting

on: [push]
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: requirements
        run: | 
          sudo apt -qq -y update
          sudo apt -qq install clang-format 
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Formatter
        run: |
          export line1='{ BasedOnStyle: LLVM, UseTab: Never,'
          export line2='IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman,'
          export line3='AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false,'
          export line4='ColumnLimit: 80, AccessModifierOffset: -4 }'
          for fname in $(find . -name '*.c' -o -name '*.h'); do clang-format -i --style="$line1 $line2 $line3 $line4" $fname; done
          
      - name: test
        run: git diff
      
