name: Doxygen CI

on: [push]
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Install requirements
        run: sudo apt -qq install doxygen dot ninja-build
      - name: configure
        run: cmake -G Ninja -B ./build -S .
      - name: build
        run: cmake --build build -t doc
