name: Doxygen CI

on: [push]
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Install requirements
        run: sudo apt -qq install doxygen graphviz ninja-build
      - name: configure
        run: cmake -G Ninja -B ./build -S .
      - name: build
        run: cmake --build build -t doc
      - name: gh-pages
        uses: actions/checkout@master
        with:
          ref: "gh-pages"
          clean: true
      # - name: cleanup
      #   run: ls -lah && rm -r !("build")
      - name: commit
        run: mv ./build/html . && rm -rf ./build && ls -lah
